version: "3.8"

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    user: root
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./terraform:/workspace/terraform
      - ./website:/workspace/website
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - DOCKER_HOST=tcp://host.docker.internal:2375
    networks:
      - portfolio_net

  terraform:
    build:
      context: .
      dockerfile: Dockerfile.terraform
    container_name: terraform
    working_dir: /workspace
    volumes:
      - ./terraform:/workspace
    networks:
      - portfolio_net

  awscli:
    build:
      context: .
      dockerfile: Dockerfile.awscli
    container_name: awscli
    working_dir: /workspace
    volumes:
      - ./website:/workspace
    networks:
      - portfolio_net

volumes:
  jenkins_home:

networks:
  portfolio_net:
    driver: bridge
