version: "3.8"

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./terraform:/workspace/terraform
      - ./website:/workspace/website
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - portfolio_net

  terraform:
    image: hashicorp/terraform:1.6.6
    container_name: terraform
    command: sleep infinity
    working_dir: /workspace
    volumes:
      - ./terraform:/workspace
    networks:
      - portfolio_net

  awscli:
    image: amazon/aws-cli:2.15.0
    container_name: awscli
    command: sleep infinity
    working_dir: /workspace
    volumes:
      - ./website:/workspace
    networks:
      - portfolio_net

volumes:
  jenkins_home:

networks:
  portfolio_net:
    driver: bridge
